import Footer from "@/components/general/Footer";
import Navbar from "@/components/general/Navbar";
import { DataProvider } from "@/context/DataContext";
import { Quicksand } from "next/font/google";
import "./globals.css";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Navbar />
          <DataProvider>{children}</DataProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
