import Navbar from "@/components/general/Navbar";
import "./globals.css";
import { Quicksand } from "next/font/google";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
